databases:
  - name: whatshouldiweartoday
    databaseName: whatshouldiweartoday
    plan: free
    user: whatshouldiweartoday

services:
  - type: web
    name: whatshouldiweartoday
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: whatshouldiweartoday
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
